//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Транспорт
    {
        public int Код_транспорта { get; set; }
        public string Марка { get; set; }
        public string Грузоподъемность { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    }
}
